name: epi2melabs-wf-cas9
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.6.0
    - pysam
    - fastcat
    - epi2melabs
    - bedtools
    - pybedtools
    - samtools
    - natsort
    - minimap2
